# Generated by Django 6.0.6 on 2026-06-07 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='auteurs/')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descriptif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('type_joueur', models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], default='particulier', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee_sortie', models.IntegerField()),
                ('photo_boite', models.ImageField(blank=True, null=True, upload_to='jeux/')),
                ('editeur', models.CharField(max_length=150)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ludotheque.jeu')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ludotheque.joueur')),
            ],
        ),
        migrations.CreateModel(
            name='ListeJeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('jeux', models.ManyToManyField(blank=True, related_name='dans_les_listes', to='ludotheque.jeu')),
                ('joueur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ma_liste', to='ludotheque.joueur')),
            ],
        ),
    ]
