# Generated by Django 6.0.6 on 2026-06-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description du jeu'),
        ),
    ]
