# Generated by Django 6.0.6 on 2026-06-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0002_jeu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='biographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
